"""
Django settings for SecurityHub project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from json import loads
from pathlib import Path
import os
import logging as _logging
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

_settings_logger = _logging.getLogger(__name__)
try:
    from dotenv import load_dotenv
    _load_dotenv = load_dotenv
except ImportError:
    _load_dotenv = lambda path: None  # noqa: E731 (env vars e.g. from Docker take precedence)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = os.path.join(BASE_DIR, '.env')
_load_dotenv(dotenv_path)

#logging.disable(logging.CRITICAL)
ADMIN_ENABLED = False


'''
Security settings, Make sure that you change the configuration before deploying the application
'''

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
USE_DOCKER = os.getenv('USE_DOCKER')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Optional dev tooling (disabled by default in Docker/production)
ENABLE_DEBUG_TOOLBAR = os.getenv("ENABLE_DEBUG_TOOLBAR", "").lower() in ("1", "true", "yes", "on")

# JWT cookie security:
# - In local Docker we serve UI over plain HTTP (e.g. http://localhost:8080), so Secure cookies would be dropped.
# - In production behind HTTPS, this should be True.
AUTH_COOKIE_SECURE = os.getenv("AUTH_COOKIE_SECURE", ("false" if DEBUG else "true")).lower() in ("1", "true", "yes", "on")

# VulnDB GitHub source — raw URL to a JSON array of vulnerability templates.
# Set to a raw.githubusercontent.com URL pointing to your community vulndb file.
VULNDB_GITHUB_URL = os.getenv("VULNDB_GITHUB_URL", "")

# Project types / report standards GitHub sources — same pattern as VulnDB above.
PROJECT_TYPES_GITHUB_URL = os.getenv("PROJECT_TYPES_GITHUB_URL", "")
REPORT_STANDARDS_GITHUB_URL = os.getenv("REPORT_STANDARDS_GITHUB_URL", "")

# CWE reference dataset, refreshed periodically by vulnerability.tasks.update_cwe_json.
# Defaults to a public CWE JSON mirror; override to point at your own fork/mirror.
CWE_DATA_GITHUB_URL = os.getenv(
    "CWE_DATA_GITHUB_URL", "https://raw.githubusercontent.com/Securityhub/securityhub-CWE/main/cwe.json"
)

ALLOWED_HOSTS = loads(os.getenv('ALLOWED_HOST', '[]'))

WHITELIST_IP = loads(os.getenv('WHITELIST_IP', '[]'))

'''
CORS Security settings
Make sure to only allow the  frontend domain/IP and not all domains Check:

https://pypi.org/project/django-cors-headers/ for more examples to configure it

Remove the CORS_ORIGIN_ALLOW_ALL = True

Set via env: CORS_ALLOWED_ORIGINS (comma-separated). Example:
  CORS_ALLOWED_ORIGINS="https://example.com,http://127.0.0.1:9000"
Parsed below.
'''

# ============================================================================
# CORS Configuration (Critical Security Setting)
# ============================================================================
# SECURITY WARNING: CORS_ORIGIN_ALLOW_ALL = True is EXTREMELY DANGEROUS!
# It allows ANY website to make authenticated requests to your API, enabling:
# - CSRF attacks
# - Session hijacking  
# - Data exfiltration
# - Compliance violations (GDPR, SOC 2)
#
# ALWAYS use explicit origin whitelist in production!
# ============================================================================

# Read allowed origins from environment variable (comma-separated list)
# Example: CORS_ALLOWED_ORIGINS="https://app.example.com,https://www.example.com"
CORS_ALLOWED_ORIGINS_STR = os.getenv('CORS_ALLOWED_ORIGINS', '')

# Development defaults (only used when DEBUG=True and no env var set)
DEV_CORS_ORIGINS = [
    "http://localhost:5173",      # Vite dev server
    "http://127.0.0.1:5173",
    "http://localhost:5174",      # Vite dev server (fallback port)
    "http://127.0.0.1:5174",
    "http://localhost:3000",      # React dev server
    "http://127.0.0.1:3000",
    "http://localhost:8000",      # Django dev server (same-origin)
    "http://127.0.0.1:8000",
    "http://localhost:80",        # Nginx
    "http://localhost",
]

if CORS_ALLOWED_ORIGINS_STR:
    # Parse comma-separated origins from environment variable
    CORS_ALLOWED_ORIGINS = [
        origin.strip() 
        for origin in CORS_ALLOWED_ORIGINS_STR.split(',') 
        if origin.strip()
    ]
    _settings_logger.info("CORS: Using %d origins from environment variable", len(CORS_ALLOWED_ORIGINS))
elif DEBUG:
    # Development mode: use defaults but log warning
    CORS_ALLOWED_ORIGINS = DEV_CORS_ORIGINS
    _settings_logger.warning("CORS: Using development defaults (DEBUG=True). Set CORS_ALLOWED_ORIGINS for production!")
else:
    # Production mode without CORS_ALLOWED_ORIGINS: CRITICAL ERROR
    raise ImproperlyConfigured(
        "CORS_ALLOWED_ORIGINS environment variable must be set in production! "
        "Example: CORS_ALLOWED_ORIGINS='https://app.example.com,https://www.example.com'"
    )

# CRITICAL: Never allow all origins (security vulnerability)
CORS_ORIGIN_ALLOW_ALL = False

# CORS Headers - All headers that can be sent in requests
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "cookie",
    "Set-Cookie",
    "x-requested-with",
    "x-csrftoken",
]

# Headers that can be accessed by the frontend
CORS_EXPOSE_HEADERS = ['Content-Disposition', 'Set-Cookie']

# Allow credentials (cookies, authorization headers) in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Allow all HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]




AUTH_USER_MODEL = 'accounts.CustomUser'


ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
#AUTH_GROUP_MODEL = 'accounts.Group'
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'vulnerability',
    'configapi',
    'project',
    'utils',
    'rest_framework',
    'corsheaders',
    'django_filters',
    # Note: weasyprint is not a Django app, it's a library
    # WeasyPrint imports are lazy-loaded to avoid startup errors if GTK+ libraries are missing
    'rest_framework_simplejwt.token_blacklist',
    'storages',
    'drf_spectacular',
    'webhooks',
    'assets',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # must be early to handle preflight OPTIONS requests
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'utils.middleware.RequestIdMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Enable Django Debug Toolbar only when explicitly opted in.
# This keeps Docker/prod images working even when dev deps aren't installed.
if DEBUG and ENABLE_DEBUG_TOOLBAR:
    try:
        import debug_toolbar  # noqa: F401
        INSTALLED_APPS.append("debug_toolbar")
        MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")
        # Keep INTERNAL_IPS reasonable for local/dev usage
        if "localhost" not in INTERNAL_IPS:
            INTERNAL_IPS.append("localhost")
    except ModuleNotFoundError:
        # If the package isn't installed, just skip it (avoid crashing the app)
        pass

PAGINATION_STANDARD_PAGE_SIZE = int(os.getenv('PAGINATION_STANDARD_PAGE_SIZE', 25))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'rest_framework_simplejwt.authentication.JWTAuthentication',
        'accounts.authenticate.CustomAuthentication'
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_RATE_ANON', '50/minute'),
        'user': os.getenv('THROTTLE_RATE_USER', '200/minute'),  # Authenticated users
        'login': os.getenv('THROTTLE_RATE_LOGIN', '5/minute'),  # Login attempts (more restrictive)
        'file_upload': os.getenv('THROTTLE_RATE_FILE_UPLOAD', '10/minute'),  # File uploads
        'search': os.getenv('THROTTLE_RATE_SEARCH', '30/minute'),  # Search operations
        'admin': os.getenv('THROTTLE_RATE_ADMIN', '500/minute'),  # Admin/superuser operations
        'burst': os.getenv('THROTTLE_RATE_BURST', '100/minute'),  # Burst protection
    },
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': PAGINATION_STANDARD_PAGE_SIZE,
    # OpenAPI schema
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ============================================================================
# Self-hosting / customization knobs
# ============================================================================
# Centralized, env-overridable settings so self-hosters running the open
# source Community Edition can tune behavior without patching code.

# Branding — shown in emails, API docs, and default report metadata.
SITE_NAME = os.getenv('SITE_NAME', 'SecurityHub')
SITE_SUPPORT_EMAIL = os.getenv('SITE_SUPPORT_EMAIL', 'support@securityhub.community')

# Pagination page sizes (utils/pagination.py reads these).
# PAGINATION_STANDARD_PAGE_SIZE is defined before REST_FRAMEWORK above.
PAGINATION_STANDARD_MAX_PAGE_SIZE = int(os.getenv('PAGINATION_STANDARD_MAX_PAGE_SIZE', 100))
PAGINATION_LARGE_PAGE_SIZE = int(os.getenv('PAGINATION_LARGE_PAGE_SIZE', 100))
PAGINATION_LARGE_MAX_PAGE_SIZE = int(os.getenv('PAGINATION_LARGE_MAX_PAGE_SIZE', 500))
PAGINATION_SMALL_PAGE_SIZE = int(os.getenv('PAGINATION_SMALL_PAGE_SIZE', 10))
PAGINATION_SMALL_MAX_PAGE_SIZE = int(os.getenv('PAGINATION_SMALL_MAX_PAGE_SIZE', 50))
PAGINATION_CURSOR_DEFAULT_LIMIT = int(os.getenv('PAGINATION_CURSOR_DEFAULT_LIMIT', 25))
PAGINATION_CURSOR_MAX_LIMIT = int(os.getenv('PAGINATION_CURSOR_MAX_LIMIT', 100))

# Max upload sizes in MB, converted to bytes (utils/input_validation.py reads this).
MAX_UPLOAD_SIZES = {
    'image': int(os.getenv('MAX_UPLOAD_MB_IMAGE', 10)) * 1024 * 1024,
    'document': int(os.getenv('MAX_UPLOAD_MB_DOCUMENT', 50)) * 1024 * 1024,
    'scan': int(os.getenv('MAX_UPLOAD_MB_SCAN', 100)) * 1024 * 1024,
    'archive': int(os.getenv('MAX_UPLOAD_MB_ARCHIVE', 200)) * 1024 * 1024,
    'default': int(os.getenv('MAX_UPLOAD_MB_DEFAULT', 50)) * 1024 * 1024,
}

# Password policy minimum length (utils/validators.MinimumLengthValidator reads this
# indirectly via AUTH_PASSWORD_VALIDATORS OPTIONS below).
PASSWORD_MIN_LENGTH = int(os.getenv('PASSWORD_MIN_LENGTH', 10))

ROOT_URLCONF = 'securityhub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'securityhub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Database configuration with automatic fallback to SQLite3
# If PostgreSQL environment variables are set, use PostgreSQL
# Otherwise, fall back to SQLite3 for local development
if all(key in os.environ for key in ['POSTGRES_DB', 'POSTGRES_USER', 'POSTGRES_PASSWORD', 'POSTGRES_HOST', 'POSTGRES_PORT']):
    # PostgreSQL configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ['POSTGRES_USER'],
            'PASSWORD': os.environ['POSTGRES_PASSWORD'],
            'HOST': os.environ['POSTGRES_HOST'],
            'PORT': os.environ['POSTGRES_PORT'],
        }
    }
else:
    # SQLite3 fallback for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }



# Cache backend: defaults to per-process in-memory caching, which is fine for a
# single-worker deployment but means cache invalidation (e.g. VulnDB/config sync
# busting a cache key) only takes effect on the worker that handled the request —
# other gunicorn workers keep serving stale data until TIMEOUT expires. Set
# REDIS_URL to share one cache across all workers/replicas.
REDIS_URL = os.getenv('REDIS_URL', '')
CACHE_TIMEOUT_SECONDS = int(os.getenv('CACHE_TIMEOUT_SECONDS', 60 * 15))

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "securityhub",
            "TIMEOUT": CACHE_TIMEOUT_SECONDS,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "KEY_PREFIX": "securityhub",
            "TIMEOUT": CACHE_TIMEOUT_SECONDS,
        }
    }

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Defense-in-depth security headers (Nginx also sets these, but Django adds another layer)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    ### Custom Validation for Password
    {
        'NAME': 'utils.validators.UppercaseValidator',
    },
    {
        'NAME': 'utils.validators.SpecialCharValidator',
    },
    {
        'NAME': 'utils.validators.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': PASSWORD_MIN_LENGTH,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('USER_TIME_ZONE')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'

USE_S3 = os.environ.get('USE_S3', 'False') == 'True'
if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = AWS_S3_ENDPOINT_URL
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

MEDIA_PATH = BASE_DIR
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
CKEDITOR_UPLOAD_LOCATION = os.path.join(MEDIA_ROOT, 'poc')

ALLOWED_TAGS = ['strong', 'em', 's', 'u', 'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'li', 'img', 'a', 'span',
                'code', 'blockquote', 'div', 'font', 'table', 'tr', 'td', 'th', 'pre', 'figure', 'figcaption', 'sup', 'thead', 'tbody', 'i', 'mark', 'label', 'sub',
                'br']

# ============================================================================
# Logging Configuration (Test-Friendly)
# ============================================================================
# Detect if we're running tests
import sys
RUNNING_TESTS = 'test' in sys.argv or 'pytest' in sys.modules

# Configure log file path (use environment variable or tempdir for tests)
if RUNNING_TESTS:
    import tempfile
    LOG_FILE_PATH = os.path.join(tempfile.gettempdir(), 'securityhub_test_debug.log')
else:
    LOG_FILE_PATH = os.getenv('LOG_FILE_PATH', os.path.join(BASE_DIR, 'logs', 'debug.log'))

# Ensure log directory exists
LOG_DIR = os.path.dirname(LOG_FILE_PATH)
if LOG_DIR and not os.path.exists(LOG_DIR):
    try:
        os.makedirs(LOG_DIR, exist_ok=True)
    except (OSError, PermissionError):
        # If we can't create log directory, disable file logging
        LOG_FILE_PATH = None
        _settings_logger.warning("Cannot create log directory %s. File logging disabled.", LOG_DIR)


def _can_write_logfile(path):
    if not path:
        return False
    try:
        log_dir = os.path.dirname(path)
        if log_dir:
            os.makedirs(log_dir, exist_ok=True)
        with open(path, 'a', encoding='utf-8'):
            pass
        return True
    except (OSError, PermissionError) as exc:
        _settings_logger.warning("Cannot write to log file %s: %s. File logging disabled.", path, exc)
        return False

try:
    import colorlog as _colorlog_check  # noqa: F401
    _COLORLOG_AVAILABLE = True
except ImportError:
    _COLORLOG_AVAILABLE = False

_CONSOLE_FORMATTER = 'color' if _COLORLOG_AVAILABLE else 'standard'

_LOGGING_FORMATTERS: dict = {
    'standard': {
        'format': '[%(levelname)s] %(asctime)-15s - %(message)s',
        'datefmt': '%d/%b/%Y %H:%M:%S',
    },
    'structured': {
        'format': '{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s","request_id":"%(request_id)s","user_id":"%(user_id)s","org_id":"%(org_id)s","path":"%(pathname)s","line":"%(lineno)d"}',
        'datefmt': '%Y-%m-%d %H:%M:%S',
    },
    'audit': {
        'format': '{"timestamp":"%(asctime)s","event_type":"%(event_type)s","action":"%(action)s","user_id":"%(user_id)s","org_id":"%(org_id)s","resource_type":"%(resource_type)s","resource_id":"%(resource_id)s","ip_address":"%(ip_address)s","request_id":"%(request_id)s"}',
        'datefmt': '%Y-%m-%d %H:%M:%S',
    },
}

if _COLORLOG_AVAILABLE:
    _LOGGING_FORMATTERS['color'] = {
        '()': 'colorlog.ColoredFormatter',
        'format': '%(log_color)s[%(levelname)s] %(asctime)-15s - %(message)s',
        'datefmt': '%d/%b/%Y %H:%M:%S',
        'log_colors': {
            'DEBUG': 'cyan',
            'INFO': 'green',
            'WARNING': 'yellow',
            'ERROR': 'red',
            'CRITICAL': 'red,bg_white',
        },
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': _LOGGING_FORMATTERS,
    'handlers': {
        'console': {
            'level': 'WARNING' if RUNNING_TESTS else 'DEBUG',  # Less verbose in tests
            'class': 'logging.StreamHandler',
            'formatter': _CONSOLE_FORMATTER,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR' if RUNNING_TESTS else 'INFO',  # Silence DB queries in tests
            'propagate': False,
        },
        'rest_framework': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'WARNING' if RUNNING_TESTS else 'DEBUG',
            'propagate': False,
        },
        'vulnerability': {
            'handlers': ['console'],
            'level': 'WARNING' if RUNNING_TESTS else 'DEBUG',
            'propagate': False,
        },
        'project': {
            'handlers': ['console'],
            'level': 'WARNING' if RUNNING_TESTS else 'DEBUG',
            'propagate': True,
        },
        'utils': {
            'handlers': ['console'],
            'level': 'WARNING' if RUNNING_TESTS else 'DEBUG',
            'propagate': False,
        },
        'audit': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Add file handler if LOG_FILE_PATH is available (not in test mode or if file is writable)
if LOG_FILE_PATH and not RUNNING_TESTS:
    if _can_write_logfile(LOG_FILE_PATH):
        # Add rotating file handler to configuration
        LOGGING['handlers']['rotating_logfile'] = {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_FILE_PATH,
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 3,
            'formatter': 'standard',
        }
        
        # Add file handler to all loggers
        LOGGING['root']['handlers'].append('rotating_logfile')
        for logger_name in LOGGING['loggers']:
            LOGGING['loggers'][logger_name]['handlers'].append('rotating_logfile')

        _settings_logger.info("Logging: File logging enabled to %s", LOG_FILE_PATH)


CKEDITOR_ALLOW_NONIMAGE_FILES = False

LOGIN_URL= '/accounts/login'



SIMPLE_JWT = {
'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 30))),
'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 7))),
'ROTATE_REFRESH_TOKENS': True,  # Keep rotation for security, but don't require blacklisting
'BLACKLIST_AFTER_ROTATION': True,  # F-21: Enabled — old refresh tokens are invalidated after rotation to prevent reuse
'ALGORITHM': 'HS256',
'SIGNING_KEY': os.getenv('SECRET_KEY'),
'VERIFYING_KEY': None,
'AUTH_HEADER_TYPES': ('Bearer',),
'USER_ID_FIELD': 'id',
'USER_ID_CLAIM': 'user_id',
'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
'TOKEN_TYPE_CLAIM': 'token_type',
'AUTH_COOKIE': 'access_token',  # Cookie name. Enables cookies if value is set.
  'AUTH_COOKIE_DOMAIN': None,     # A string like "example.com", or None for standard domain cookie.
  'AUTH_COOKIE_SECURE': AUTH_COOKIE_SECURE,    # Whether the auth cookies should be secure (https:// only).
  'AUTH_COOKIE_HTTP_ONLY' : True, # Http only cookie flag.It's not fetch by javascript.
  'AUTH_COOKIE_PATH': '/',        # The path of the auth cookie.
  'AUTH_COOKIE_SAMESITE': 'Lax',
}



# Email Configuration
USE_EMAIL = os.getenv('USE_EMAIL')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f'{SITE_NAME} <{SITE_SUPPORT_EMAIL}>')

# Email timeout settings
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 60))  # seconds

# Configure if using an email service with rate limits
EMAIL_THROTTLE = os.getenv('EMAIL_THROTTLE', 'False') == 'True'
EMAIL_THROTTLE_RATE = int(os.getenv('EMAIL_THROTTLE_RATE', 100))  # Max emails per day

# Frontend URL for email links
FRONTEND_URL = os.getenv('FRONTEND_URL')

# OpenAPI/Swagger Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': f'{SITE_NAME} API Documentation',
    'DESCRIPTION': f'{SITE_NAME} - Complete API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAuthenticated'],
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    'SORT_OPERATIONS': False,
    'SECURITY': [
        {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    ],
    'AUTHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'accounts.authenticate.CustomAuthentication',
    ],
    'ENUM_NAME_OVERRIDES': {
        'StatusChoices': 'project.models.STATUS_CHOICES',
        'ProjectStatusChoices': 'project.models.PROJECT_STATUS_CHOICES',
    },
    'SCHEMA_PATH_PREFIX': '/api/',
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and token management'},
        {'name': 'Users', 'description': 'User management and permissions'},
        {'name': 'Customers', 'description': 'Customer management and dashboards'},
        {'name': 'Projects', 'description': 'Project management and lifecycle'},
        {'name': 'Vulnerabilities', 'description': 'Vulnerability management'},
        {'name': 'Scopes', 'description': 'Project scope management'},
        {'name': 'Dashboard', 'description': 'Analytics and dashboard APIs'},
        {'name': 'Parser', 'description': 'Scanner integration and file parsing'},
        {'name': 'Configuration', 'description': 'System configuration and health checks'},
    ],
    'EXTENSIONS_INFO': {
        'x-logo': {
            'url': '/static/logo.png',
            'altText': f'{SITE_NAME} Logo'
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True,
        'requestInterceptor': '''
            function(request) {
                // Ensure Authorization header is included
                if (window.ui && window.ui.authActions) {
                    const auth = window.ui.authActions.getAuthorized();
                    if (auth && auth.Bearer && auth.Bearer.value) {
                        let token = auth.Bearer.value;
                        // Remove "Bearer " prefix if it's already there
                        if (token.startsWith('Bearer ')) {
                            token = token.substring(7);
                        }
                        request.headers['Authorization'] = 'Bearer ' + token;
                    }
                }
                return request;
            }
        ''',
        'responseInterceptor': 'function(response) { return response; }',
    },
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'expandResponses': '200,201',
        'pathInMiddlePanel': True,
    },
}
