# Generated by Django 4.2.22 on 2026-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='response_body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
