# Generated by Django 6.0.6 on 2026-06-17 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AUDIT', 'Audit Event'), ('SECURITY_EVENT', 'Security Event'), ('DATA_ACCESS', 'Data Access')], db_index=True, default='AUDIT', help_text='Type of audit event', max_length=50)),
                ('user_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('org_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(db_index=True, help_text='Action performed', max_length=100)),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='Type of resource (Project, User, Vulnerability, etc.)', max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional event details as JSON', null=True)),
                ('security_event', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('compliance_required', models.BooleanField(db_index=True, default=False)),
                ('security_required', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['user', '-timestamp'], name='audit_log_user_id_79f582_idx'), models.Index(fields=['org_id', '-timestamp'], name='audit_log_org_id_7a40f7_idx'), models.Index(fields=['action', '-timestamp'], name='audit_log_action_cf8063_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx'), models.Index(fields=['event_type', '-timestamp'], name='audit_log_event_t_37db9c_idx'), models.Index(fields=['compliance_required', '-timestamp'], name='audit_log_complia_be0e59_idx'), models.Index(fields=['security_required', '-timestamp'], name='audit_log_securit_5e5250_idx')],
            },
        ),
    ]
