# Generated by Django 6.0.6 on 2026-06-17 21:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('word', 'Word'), ('docx', 'DOCX'), ('csv', 'CSV'), ('latex', 'LaTeX')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('executive', 'Executive'), ('technical', 'Technical'), ('compliance', 'Compliance'), ('custom', 'Custom')], db_index=True, default='custom', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('content', models.TextField()),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('current_version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_system_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(db_index=True)),
                ('content', models.TextField()),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_name', models.CharField(db_index=True, default='main', max_length=100)),
                ('is_merged', models.BooleanField(default=False)),
                ('is_tagged', models.BooleanField(default=False)),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_template_versions', to=settings.AUTH_USER_MODEL)),
                ('merge_base_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from_versions', to='configapi.templateversion')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='configapi.templateversion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='configapi.reporttemplate')),
            ],
            options={
                'db_table': 'template_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['format', 'category'], name='report_temp_format_915040_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_public', 'is_active'], name='report_temp_is_publ_0031f1_idx'),
        ),
        migrations.AddIndex(
            model_name='templateversion',
            index=models.Index(fields=['template', 'version_number'], name='template_ve_templat_bfbc62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateversion',
            unique_together={('template', 'version_number')},
        ),
    ]
