from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vulnerability',
            name='vuln_cisa_kev_idx',
        ),
        migrations.RemoveIndex(
            model_name='vulnerability',
            name='vuln_epss_idx',
        ),
        migrations.RemoveIndex(
            model_name='vulnerability',
            name='vuln_intel_score_idx',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='has_cisa_kev_exploit',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='epss_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='epss_percentile',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='aqua_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='inspector_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='nvd_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='nvd_score_v3',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='final_intelligence_score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='intelligence_metadata',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='correlation_data',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='enrichment_data',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='last_intelligence_update',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='enrichment_last_updated',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='intelligence_confidence',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='threat_level',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='data_sources',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='kev_urgency_level',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='exploit_types',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='metasploit_modules',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='asset_context',
        ),
    ]
