# Generated by Django 4.2.22 on 2026-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_add_finding_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slapolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
